workflows:
  android-release:
    name: Android Release (Flutter)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
      groups:
        - keystore_credentials
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter --version
          flutter clean
          flutter pub get
      - name: Build APK (release)
        script: |
          export JAVA_HOME="$JAVA_HOME"
          echo "Using JAVA_HOME=$JAVA_HOME"
          flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.{apk,aab}
    publishing:
      email:
        recipients:
          - chikeeluem171@gmail.com
        notify:
          success: true
          failure: true
