workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android: latest
      vars:
        PACKAGE_NAME: "com.cyber_ai_app"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Run code generation (if using build_runner)
        script: |
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
      - name: Clean Android build
        script: |
          cd android
          ./gradlew clean
      - name: Build release APK
        script: |
          cd ..
          flutter build apk --release --flavor prod
    artifacts:
      - build/app/outputs/flutter-apk/app-prod-release.apk
    publishing:
      email:
        recipients:
          - chikeeluem171@gmail.com
