name: cyber_ai_app
description: CyberAI - final year project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.5.1

  # UI
  google_fonts: ^6.2.1
  animations: ^2.0.11
  lottie: ^3.1.2

  # Networking & utils
  dio: ^5.7.0
  network_info_plus: ^6.0.1
  permission_handler: ^11.3.1
  timezone: ^0.9.3

  # Local storage & notifications
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.2.1
  android_alarm_manager_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/knowledge_base.json
