name: cyber_ai
description: Cyber-Ai - Android app
publish_to: 'none' # private app

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # Core & utility packages
  characters: ^1.4.1
  intl: ^0.20.2
  material_color_utilities: ^0.13.0

  # Platform / plugins (updated)
  flutter_local_notifications: ^19.4.1
  flutter_local_notifications_linux: ^6.0.0
  flutter_local_notifications_platform_interface: ^9.1.0
  network_info_plus: ^6.1.4
  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
