name: cyber_ai_app
description: CyberAI — Flutter cybersecurity assistant with offline KB, memory, tools, notifications, and optional proxy.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.2.3
  animations: ^2.0.11
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  permission_handler: ^11.3.0
  network_info_plus: ^5.0.3
  android_alarm_manager_plus: ^4.0.8
  path_provider: ^2.1.3
  intl: ^0.19.0
  uuid: ^4.4.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/anim/
    - assets/data/
