name: Flutter Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'   # Adjust if your project needs another version

      # Setup Java (needed for Gradle/Android builds)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Accept SDK Licenses (fixes license issues)
      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      # Install dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # Build Debug APK
      - name: Build Debug APK
        run: flutter build apk --debug

      # Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      # Build Release AppBundle (Play Store)
      - name: Build Release AppBundle
        run: flutter build appbundle --release

      # Upload Release AppBundle
      - name: Upload Release AAB
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
