name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout source code
        uses: actions/checkout@v4

      # Setup Java (required for Android builds)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'   # ✅ Stable with Dart >=3.5
          channel: stable
          cache: true

      # Accept Android licenses
      - name: Accept Android SDK licenses
        run: yes | flutter doctor --android-licenses

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run static analysis
      - name: Analyze project source
        run: flutter analyze

      # Run tests (if you have any)
      - name: Run tests
        run: flutter test || true

      # Build debug APK (for quick testing)
      - name: Build debug APK
        run: flutter build apk --debug

      # Build release AAB (Play Store upload)
      - name: Build release App Bundle
        run: flutter build appbundle --release

      # Save build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/app/outputs/
